### ISSUE TITLE
fatal: not a git repository:

### ISSUE THREAD

**Issue by yansheng836** [shenxianpeng/gitstats#25]
When I use this tool, has a error

the local git repo is <https://github.com/hoxu/gitstats>

```shell
user@LAPTOP-VVFGEHP8 MINGW64 /f/workspace/plain-project/gitstats (master)
$ gitstats ./ ./tmp
[0.58825] >> gnuplot --version
Output path: F:\workspace\plain-project\gitstats\tmp
Git path: ./
Collecting data...
[0.14703] >> git shortlog -s HEAD | wc -l
[0.12075] >> git show-ref --tags
[0.10382] >> git rev-list --pretty=format:"%at %ai %aN <%aE>" HEAD | grep -v ^commit
[0.09662] >> git rev-list --pretty=format:"%at %T" HEAD | grep -v ^commit
[0.22905] >> git ls-tree -r --name-only "a7e9c4c39228ba183acea2489b90e6c5eda7f919" | wc -l
……
[0.07872] >> git ls-tree -r --name-only "d596df2995999c2e3f90fef180bbe683474fcb53" | wc -l
[0.07407] >> git ls-tree -r -l -z HEAD
[0.13580] >> git cat-file blob 15eabb351ae57f58f1eec230195ba52f543352ff | wc -l
……
[0.22546] >> git cat-file blob c71b0e440882917b9fcb5d0b3f9dd43d818b39d8 | wc -l
[0.11170] >> git log --shortstat --first-parent -m --pretty=format:"%at %aN" HEAD
[0.11642] >> git log --shortstat --date-order --pretty=format:"%at %aN" HEAD
Refining data...
Saving cache...
Generating report...
fatal: not a git repository: 'F:\Python\Python312\Lib\site-packages\gitstats/.git'
[0.06380] >> git --git-dir=F:\Python\Python312\Lib\site-packages\gitstats/.git --work-tree=F:\Python
\Python312\Lib\site-packages\gitstats rev-parse --short HEAD
[0.06982] >> git --version
[0.19603] >> gnuplot --version
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "F:\Python\Python312\Scripts\gitstats.exe\__main__.py", line 7, in <module>
  File "F:\Python\Python312\Lib\site-packages\gitstats\main.py", line 1851, in main
    g.run(sys.argv[1:])
  File "F:\Python\Python312\Lib\site-packages\gitstats\main.py", line 1827, in run
    report.create(data, outputpath)
  File "F:\Python\Python312\Lib\site-packages\gitstats\main.py", line 1220, in create
    f.write(
UnicodeEncodeError: 'gbk' codec can't encode character '\xd8' in position 146: illegal multibyte seq
uence

```

my env

gitstats               0.3.2
GNUPLOT Version 5.2.6

**Comment by yansheng836** [comment]
althouth it has a error,the tmp dir have some file. I don't know if all.

```shell
$ ls tmp/
activity.html   arrow-up.gif         commits_by_year_month.dat  gitstats.css     month_of_year.dat
arrow-down.gif  authors.html         day_of_week.dat            hour_of_day.dat  sortable.js
arrow-none.gif  commits_by_year.dat  gitstats.cache             index.html

```
But the 4-6 page is lost
![image](https://github.com/user-attachments/assets/82802560-2320-4e19-8b5f-0099d3d49096)

**Comment by yansheng836** [comment]
And later I use for another repo(which has 700+ commit),it work.
I gauss it maybe some reason for this repo(https://github.com/hoxu/gitstats) , If you can use this repo to find some problems is also good, if it can not be repeated, then close it.

**Comment by yansheng836** [comment]
> The repo https://github.com/hoxu/gitstats is dead.
> 
> I haven't encountered any errors or issues on Linux, so it may be related to the Windows platform?
> 
> For example, here’s a report showcasing data from the Jenkins project: https://shenxianpeng.github.io/gitstats/examples/jenkins/files.html
> 
> You can follow the steps outlined for Linux as bellow: https://github.com/shenxianpeng/gitstats/blob/main/.github/workflows/examples.yml#L22-L28

Yes,I use it on my local windows.

**Comment by yansheng836** [comment]
Simple reading wrong information, is caused by coding problems, do not know whether the user name is caused by Chinese.

For this repo: https://github.com/Tencent/TBase , it also with this error(`fatal: not a git repository: `)

```
……
[3.74644] >> git log --shortstat --date-order --pretty=format:"%at %aN" HEAD
Refining data...
Saving cache...
Generating report...
fatal: not a git repository: 'F:\Python\Python312\Lib\site-packages\gitstats/.git'
[0.06501] >> git --git-dir=F:\Python\Python312\Lib\site-packages\gitstats/.git --work-tree=F:\Python
\Python312\Lib\site-packages\gitstats rev-parse --short HEAD
[0.06167] >> git --version
[0.14328] >> gnuplot --version
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "F:\Python\Python312\Scripts\gitstats.exe\__main__.py", line 7, in <module>
  File "F:\Python\Python312\Lib\site-packages\gitstats\main.py", line 1851, in main
    g.run(sys.argv[1:])
  File "F:\Python\Python312\Lib\site-packages\gitstats\main.py", line 1827, in run
    report.create(data, outputpath)
  File "F:\Python\Python312\Lib\site-packages\gitstats\main.py", line 1220, in create
    f.write(
UnicodeEncodeError: 'gbk' codec can't encode character '\u26a1' in position 338: illegal multibyte s
equence


```

**Comment by yansheng836** [comment]
For this repo: https://github.com/Tencent/TBase , it also with this error(`fatal: not a git repository: `) .
But it executed successfully and was able to view the report normally.

```
……
[3.46076] >> git log --shortstat --date-order --pretty=format:"%at %aN" HEAD
Refining data...
Saving cache...
Generating report...
fatal: not a git repository: 'F:\Python\Python312\Lib\site-packages\gitstats/.git'
[0.05802] >> git --git-dir=F:\Python\Python312\Lib\site-packages\gitstats/.git --work-tree=F:\Python
\Python312\Lib\site-packages\gitstats rev-parse --short HEAD
[0.06339] >> git --version
[0.17034] >> gnuplot --version
Generating graphs...
[0.20438] >> gnuplot "F:\workspace\C-project\TBase\tmp\commits_by_author.plot"
[0.17163] >> gnuplot "F:\workspace\C-project\TBase\tmp\commits_by_year.plot"
[0.45171] >> gnuplot "F:\workspace\C-project\TBase\tmp\commits_by_year_month.plot"
[0.27280] >> gnuplot "F:\workspace\C-project\TBase\tmp\day_of_week.plot"
[0.18954] >> gnuplot "F:\workspace\C-project\TBase\tmp\domains.plot"
[0.17016] >> gnuplot "F:\workspace\C-project\TBase\tmp\files_by_date.plot"
[0.18687] >> gnuplot "F:\workspace\C-project\TBase\tmp\hour_of_day.plot"
[0.17308] >> gnuplot "F:\workspace\C-project\TBase\tmp\lines_of_code.plot"
[0.20427] >> gnuplot "F:\workspace\C-project\TBase\tmp\lines_of_code_by_author.plot"
[0.17168] >> gnuplot "F:\workspace\C-project\TBase\tmp\month_of_year.plot"
Execution time 197.40855 secs, 11.43133 secs (5.79 %) in external commands)
You may now run:

   sensible-browser 'F:\workspace\C-project\TBase\tmp\index.html'

```
